<a href="https://colab.research.google.com/github/teju3805/LLM/blob/main/self_attention_and_multi_head_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn.functional as F

# Take sentence from user
text = input("Enter a sentence: ")

# Tokenize sentence
tokens = text.split()

# Create embeddings
embeddings = torch.rand(len(tokens), 8)

num_heads = 2
head_dim = embeddings.size(1) // num_heads

for h in range(num_heads):
    Q = embeddings[:, h*head_dim:(h+1)*head_dim]
    K = Q
    V = Q

    # Attention scores
    scores = torch.matmul(Q, K.T)

    # Attention weights
    weights = F.softmax(scores, dim=1)

    # Context vectors
    context_vectors = torch.matmul(weights, V)

    print(f"\n========== Head {h+1} ==========")

    print("\nAttention Scores:")
    print(scores)

    print("\nAttention Weights:")
    print(weights)

    print("\nContext Vectors:")
    for i, word in enumerate(tokens):
        print(f"Context vector for '{word}' (Head {h+1}):")
        print(context_vectors[i])


Enter a sentence: apple is a fruit

========== Head 1 ==========

Attention Scores:
tensor([[2.9999, 1.9805, 2.6105, 1.5647],
        [1.9805, 1.5090, 1.9128, 1.0383],
        [2.6105, 1.9128, 2.4800, 1.4094],
        [1.5647, 1.0383, 1.4094, 0.9747]])

Attention Weights:
tensor([[0.4393, 0.1585, 0.2976, 0.1046],
        [0.3392, 0.2117, 0.3170, 0.1322],
        [0.3737, 0.1860, 0.3279, 0.1124],
        [0.3332, 0.1968, 0.2853, 0.1847]])

Context Vectors:
Context vector for 'apple' (Head 1):
tensor([0.7742, 0.8796, 0.7171, 0.6039])
Context vector for 'is' (Head 1):
tensor([0.7357, 0.8625, 0.7139, 0.5503])
Context vector for 'a' (Head 1):
tensor([0.7536, 0.8716, 0.7231, 0.5716])
Context vector for 'fruit' (Head 1):
tensor([0.7284, 0.8565, 0.6792, 0.5370])

========== Head 2 ==========

Attention Scores:
tensor([[1.1013, 1.2008, 0.5223, 0.7542],
        [1.2008, 1.8853, 0.5782, 0.7227],
        [0.5223, 0.5782, 0.2515, 0.3537],
        [0.7542, 0.7227, 0.3537, 0.5870]])

Attention Weight

In [ ]:
import torch
import torch.nn.functional as F

# Take sentence from user
text = input("Enter a sentence: ")

# Tokenize sentence
tokens = text.split()

# Create random embeddings for each token
embeddings = torch.rand(len(tokens), 8)

# Query, Key, Value matrices
Q = embeddings
K = embeddings
V = embeddings

# Compute attention scores (Q × K^T)
attention_scores = torch.matmul(Q, K.T)

# Normalize scores using softmax
attention_weights = F.softmax(attention_scores, dim=1)

# Compute context vectors (Attention Output)
context_vectors = torch.matmul(attention_weights, V)

# Print attention scores
print("\nAttention Scores:")
print(attention_scores)

# Print attention weights
print("\nAttention Weights:")
print(attention_weights)

# Print context vector for each word
print("\nContext Vectors for Each Word:")
for i, word in enumerate(tokens):
    print(f"Context vector for '{word}':")
    print(context_vectors[i])


Enter a sentence: apple is a fruit

Attention Scores:
tensor([[1.6416, 1.3058, 1.1515, 1.1577],
        [1.3058, 2.6838, 1.3656, 1.8483],
        [1.1515, 1.3656, 1.9442, 0.9666],
        [1.1577, 1.8483, 0.9666, 2.0680]])

Attention Weights:
tensor([[0.3397, 0.2428, 0.2081, 0.2094],
        [0.1291, 0.5119, 0.1370, 0.2220],
        [0.1894, 0.2346, 0.4185, 0.1574],
        [0.1586, 0.3163, 0.1310, 0.3941]])

Context Vectors for Each Word:
Context vector for 'apple':
tensor([0.3739, 0.3254, 0.4114, 0.5767, 0.4638, 0.4534, 0.3282, 0.4469])
Context vector for 'is':
tensor([0.4812, 0.4752, 0.4014, 0.7757, 0.2962, 0.5208, 0.3443, 0.3484])
Context vector for 'a':
tensor([0.3402, 0.2678, 0.4960, 0.4890, 0.4068, 0.6220, 0.3355, 0.4010])
Context vector for 'fruit':
tensor([0.4879, 0.3371, 0.3322, 0.7563, 0.3271, 0.4401, 0.4020, 0.4067])
